dist: trusty
sudo: false

language: node_js
node_js:
  - "10"

before_deploy:
  - export TRAVIS_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))

cache:
  directories:
    - ./node_modules

install:
  - npm install

jobs:
  include:
    - stage: lint
      if: type = pull_request OR type = push AND branch = master
      name: "Linting Angular Application ..."
      script: ng lint
    - stage: build
      if: type = push AND branch != master
      name: "Building Angular Application ..."
      script: npm run ng:build
    - stage: build
      if: type = push AND branch = master
      name: "Building Electron Application ..."
      script: npm run pack
    - stage: deploy
      if: type = push AND branch = master
      name: "Deploying GitHub Releases ..."
      script:
        - git config --global user.email "timon.gaebelein@icloud.com"
        - git config --global user.name "UnchartedBull"
        - git config --global push.default matching
        - git config credential.helper "store --file=.git/credentials"
        - echo "https://${GITHUB_API_KEY}:@github.com" > .git/credentials
        - .travis/bump-version.sh
        - npm run pack
        - mv package/*armv7l.deb OctoDash_$(git describe --tags $(git rev-list --tags --max-count=1))_armv7l.deb
        - mv package/*arm64.deb OctoDash_$(git describe --tags $(git rev-list --tags --max-count=1))_arm64.deb
        - export TRAVIS_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        skip_cleanup: true
        draft: true
        on:
          tags: true
        file_glob: true
        file:
          - "OctoDash_*_armv7l.deb"
          - "OctoDash_*_arm64.deb"
